version: '3.1'
services:
  reactmap:
    image: ghcr.io/watwowmap/reactmap:main #pr-10
    container_name: reactmap
    command: sh -c "yarn migrate:latest && yarn start"
    restart: unless-stopped
    volumes:
      - ./server/src/configs/areas.json:/home/node/server/src/configs/areas.json
      - ./server/src/configs/config.json:/home/node/server/src/configs/config.json
      - ./env.example:/home/node/env.example
    ports:
      - "9090:8080"
